/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Conversation {
  drugName: string;
  id: string;
  messages: string;
  thumbnail: string;
  userId: string;
}

export interface User {
  email: string;
  id: string;
  password: string;
}

export interface UserSession {
  id: string;
  userId: string;
}

export interface DB {
  conversation: Conversation;
  user: User;
  userSession: UserSession;
}
